name: V8 Build

on:
  workflow_call:

jobs:
  setup-and-build-v8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git python3 python3-pip curl lldb llvm || echo "⚠️ Warning: Some dependencies failed to install, continuing..."

      - name: Clone depot_tools
        run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

      - name: Add depot_tools to PATH
        run: echo "${{ github.workspace }}/depot_tools" >> $GITHUB_PATH

      - name: Fetch V8
        run: |
          fetch v8
          cd v8
          gclient sync || echo "⚠️ Warning: gclient sync failed, continuing..."
      
      - name: Install V8 build dependencies
        run: |
          ./build/install-build-deps.sh || echo "⚠️ Warning: install-build-deps.sh failed, continuing..."
        working-directory: v8

      - name: Build V8
        run: |
          gn gen out.gn/x64.release --args='is_debug=false target_cpu="x64"'
          ninja -C out.gn/x64.release || echo "⚠️ Warning: V8 build failed, profiling may not work."
        working-directory: v8
