name: V8 Environment Setup & Code Familiarization

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  setup-v8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential curl libcap-dev libncurses5-dev python3 python3-pip python3-setuptools python3-wheel unzip zlib1g-dev llvm-11 llvm-11-dev clang-11 python3-dev libffi-dev libssl-dev

      - name: Install Depot Tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git $HOME/depot_tools
          echo 'export PATH=$PATH:$HOME/depot_tools' >> $HOME/.bashrc
          source $HOME/.bashrc
          gclient --version

      - name: Clone V8 Repository
        run: |
          git clone https://chromium.googlesource.com/v8/v8
          cd v8
          gclient sync

      - name: Build V8
        run: |
          cd v8
          tools/dev/gm.py x64.release

      - name: Run V8 Tests
        run: |
          cd v8
          tools/run-tests.py --outdir=out/x64.release

      - name: Install Angr
        run: |
          pip3 install angr

      - name: Install KLEE
        run: |
          git clone https://github.com/klee/klee.git
          cd klee
          mkdir build
          cd build
          cmake .. -DENABLE_SOLVERS=STP -DENABLE_POSIX_RUNTIME=ON -DLLVM_CONFIG_BINARY=$(which llvm-config-11)
          make -j$(nproc)
          sudo make install
          klee --version

      - name: Install QSYM
        run: |
          git clone https://github.com/sslab-gatech/qsym.git
          cd qsym
          pip3 install -r requirements.txt
          sudo python3 setup.py install
