name: V8 Interpreter Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test-v8:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies (Ensure Bash Exists)
        run: |
          sudo apt update
          sudo apt install -y bash git python3 python3-pip curl lldb llvm clang build-essential
          if ! command -v bash &> /dev/null; then
            echo "❌ Bash installation failed!"
            exit 1
          fi
        shell: bash

      - name: Clone depot_tools
        run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        shell: bash

      - name: Add depot_tools to PATH
        run: |
          echo "${{ github.workspace }}/depot_tools" >> $GITHUB_PATH
          export PATH="${{ github.workspace }}/depot_tools:$PATH"
          source ~/.bashrc
          command -v fetch || { echo "❌ fetch command not found!"; exit 1; }
        shell: bash

      - name: Fetch V8 with Retry
        run: |
          retry() {
            local n=1
            local max=3
            local delay=5
            while true; do
              "$@" && break || {
                if [[ $n -lt $max ]]; then
                  ((n++))
                  echo "❌ Attempt $n/$max failed! Retrying in $delay seconds..."
                  sleep $delay
                else
                  echo "❌ Maximum attempts reached. Exiting..."
                  exit 1
                fi
              }
            done
          }
          retry fetch v8
        env:
          PATH: "${{ github.workspace }}/depot_tools:${PATH}"
        shell: bash

      - name: Sync V8 Dependencies
        run: |
          retry gclient sync
        working-directory: v8
        env:
          PATH: "${{ github.workspace }}/depot_tools:${PATH}"
        shell: bash

      - name: Install V8 Build Dependencies
        run: sudo ./build/install-build-deps.sh
        working-directory: v8
        shell: bash

      - name: Build V8
        run: |
          gn gen out.gn/x64.release --args='is_debug=false target_cpu="x64"'
          ninja -C out.gn/x64.release d8 cctest
        working-directory: v8
        shell: bash

      - name: Run cctest Suite (Interpreter Tests)
        run: |
          out.gn/x64.release/cctest --gtest_filter=Interpreter*
        working-directory: v8
        shell: bash

      - name: Run Ignition Tests
        run: |
          if [ -d "test/interpreter" ]; then
            tools/run-tests.py --outdir=out.gn/x64.release interpreter/
          else
            echo "❌ Interpreter test suite not found!"
            exit 1
          fi
        working-directory: v8
        shell: bash

      - name: Run mjsunit Tests
        run: |
          tools/run-tests.py --outdir=out.gn/x64.release mjsunit/
        working-directory: v8
        shell: bash

      - name: Run Test262 Suite
        run: |
          tools/run-tests.py --outdir=out.gn/x64.release --download-data test262
          tools/run-tests.py --outdir=out.gn/x64.release test262
        working-directory: v8
        shell: bash

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: v8-test-results
          path: v8/out.gn/x64.release/test-results.xml
