name: V8 Interpreter Comprehensive Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test-v8:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          set -e
          sudo apt update
          sudo apt install -y git python3 python3-pip curl lldb llvm clang build-essential

      - name: Clone depot_tools
        run: |
          set -e
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

      - name: Add depot_tools to PATH
        run: |
          set -e
          echo "${{ github.workspace }}/depot_tools" >> $GITHUB_PATH

      - name: Fetch V8
        run: |
          set -e
          fetch v8
        env:
          PATH: "${{ github.workspace }}/depot_tools:${PATH}"

      - name: Sync V8 Dependencies
        run: |
          set -e
          gclient sync
        working-directory: v8
        env:
          PATH: "${{ github.workspace }}/depot_tools:${PATH}"

      - name: Install V8 Build Dependencies
        run: |
          set -e
          sudo ./build/install-build-deps.sh
        working-directory: v8

      - name: Build V8
        run: |
          set -e
          gn gen out.gn/x64.release --args='is_debug=false target_cpu="x64"'
          ninja -C out.gn/x64.release d8 cctest
        working-directory: v8

      - name: Run cctest Suite
        run: |
          set -e
          out.gn/x64.release/cctest --gtest_filter=Interpreter*
        working-directory: v8

      - name: Run mjsunit Tests
        run: |
          set -e
          tools/run-tests.py --outdir=out.gn/x64.release mjsunit/
        working-directory: v8

      - name: Run Test262 Suite
        run: |
          set -e
          tools/run-tests.py --outdir=out.gn/x64.release --download-data test262
          tools/run-tests.py --outdir=out.gn/x64.release test262
        working-directory: v8

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: v8-test-results
          path: v8/out.gn/x64.release/test-results.xml
