name: V8 Interpreter Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test-v8:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Bash Installation
        run: |
          if command -v bash &> /dev/null; then
            echo "✅ Bash is installed at $(which bash)"
          else
            echo "❌ Bash is not installed!"
            exit 1
          fi
        shell: bash

      - name: Install Core Utilities
        run: sudo apt-get install -y coreutils
        shell: bash

      - name: Clone depot_tools
        run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        shell: bash

      - name: Add depot_tools to PATH
        run: |
          echo "${{ github.workspace }}/depot_tools" >> $GITHUB_PATH
          export PATH="${{ github.workspace }}/depot_tools:$PATH"
        shell: bash

      - name: Fetch V8 with Retry
        run: |
          for i in {1..3}; do
            fetch v8 && break || {
              echo "Attempt $i failed. Retrying in 5 seconds..."
              sleep 5
            }
          done
        env:
          PATH: "${{ github.workspace }}/depot_tools:${PATH}"
        shell: bash

      - name: Sync V8 Dependencies
        run: gclient sync
        working-directory: v8
        env:
          PATH: "${{ github.workspace }}/depot_tools:${PATH}"
        shell: bash

      - name: Install V8 Build Dependencies
        run: sudo ./build/install-build-deps.sh
        working-directory: v8
        shell: bash

      - name: Build V8
        run: |
          gn gen out.gn/x64.release --args='is_debug=false target_cpu="x64"'
          ninja -C out.gn/x64.release d8 cctest
        working-directory: v8
        shell: bash

      - name: Run cctest Suite
        run: out.gn/x64.release/cctest --gtest_filter=Interpreter*
        working-directory: v8
        shell: bash

      - name: Run Ignition Tests
        run: |
          if [ -d "test/interpreter" ]; then
            tools/run-tests.py --outdir=out.gn/x64.release interpreter/
          else
            echo "❌ Interpreter test suite not found!"
            exit 1
          fi
        working-directory: v8
        shell: bash

      - name: Run mjsunit Tests
        run: tools/run-tests.py --outdir=out.gn/x64.release mjsunit/
        working-directory: v8
        shell: bash

      - name: Run Test262 Suite
        run: |
          tools/run-tests.py --outdir=out.gn/x64.release --download-data test262
          tools/run-tests.py --outdir=out.gn/x64.release test262
        working-directory: v8
        shell: bash

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: v8-test-results
          path: v8/out.gn/x64.release/test-results.xml
