name: V8 Environment Setup & Code Familiarization

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-v8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-venv git clang lld llvm cmake ninja-build curl

      - name: Verify Python Installation
        run: |
          python3 --version
          pip3 --version

      - name: Clone V8 Repository
        run: |
          git clone https://chromium.googlesource.com/v8/v8
          cd v8
          ls -l build/ || echo "No build/ directory found!"
          ls -l || echo "Listing v8 root directory..."

      - name: Install Gclient & Sync Dependencies
        run: |
          sudo apt install -y depot-tools
          echo 'export PATH=$PATH:$HOME/depot_tools' >> ~/.bashrc
          source ~/.bashrc
          gclient --version || echo "Gclient is not installed correctly!"
          cd v8
          gclient sync || echo "Gclient sync failed!"

      - name: Install Build Dependencies (if available)
        run: |
          cd v8
          if [ -f build/install-build-deps.sh ]; then
            chmod +x build/install-build-deps.sh
            ./build/install-build-deps.sh
          else
            echo "WARNING: install-build-deps.sh not found!"
          fi

      - name: Build V8
        run: |
          cd v8
          tools/dev/gm.py x64.release || echo "V8 build failed!"

      - name: Verify V8 Installation
        run: |
          cd v8
          tools/run-tests.py --outdir=out/x64.release || echo "V8 test suite failed!"

      - name: Install Symbolic Execution Tools
        run: |
          pip install angr
          sudo apt install -y klee
          git clone https://github.com/sslab-gatech/qsym.git
