name: V8 Environment Setup & Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup-and-build-v8:
    runs-on: ubuntu-latest
    env:
      DEPOT_TOOLS_UPDATE: 0

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git python3 python3-pip python-is-python3
        sudo apt install -y llvm clang cmake ninja-build

    - name: Clone depot_tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "::add-path::$(pwd)/depot_tools"

    - name: Fetch V8
      run: |
        mkdir v8
        cd v8
        fetch v8
        gclient sync

    - name: Build V8
      run: |
        cd v8
        tools/dev/gm.py x64.release
        tools/run-tests.py --outdir=out/x64.release
