name: V8 Environment Setup & Profiling

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup-and-profile-v8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git python3 python3-pip curl lldb llvm || echo "⚠️ Warning: Some dependencies failed to install, continuing..."

      - name: Clone depot_tools
        run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

      - name: Add depot_tools to PATH
        run: echo "${{ github.workspace }}/depot_tools" >> $GITHUB_PATH

      - name: Fetch V8
        run: |
          fetch v8
          cd v8
          gclient sync || echo "⚠️ Warning: gclient sync failed, continuing..."
      
      - name: Install V8 build dependencies
        run: |
          ./build/install-build-deps.sh || echo "⚠️ Warning: install-build-deps.sh failed, continuing..."
        working-directory: v8

      - name: Build V8
        run: |
          gn gen out.gn/x64.release --args='is_debug=false target_cpu="x64"'
          ninja -C out.gn/x64.release || echo "⚠️ Warning: V8 build failed, profiling may not work."
        working-directory: v8

      - name: Run Ignition Tests
        run: |
          tools/run-tests.py --outdir=out.gn/x64.release interpreter/ || echo "⚠️ Warning: Ignition tests failed, continuing..."
        working-directory: v8

      - name: Install Symbolic Execution Tools
        run: |
          pip install angr || echo "⚠️ Warning: Angr installation failed, continuing..."
          sudo apt install -y llvm klee || echo "⚠️ Warning: KLEE installation failed, continuing..."
          git clone https://github.com/sslab-gatech/qsym.git || echo "⚠️ Warning: QSYM clone failed, continuing..."
        working-directory: v8

      - name: Instrument Ignition for Profiling
        run: |
          echo "Compiling V8 with Ignition instrumentation..."
          gn gen out.gn/x64.instrumented --args='is_debug=true target_cpu="x64" v8_enable_symbolic_execution=true'
          ninja -C out.gn/x64.instrumented || echo "⚠️ Warning: Instrumented build failed, profiling may not work."
        working-directory: v8

      - name: Run Symbolic Execution Profiling
        run: |
          if [ ! -f scripts/profile_ignition.py ]; then
            echo "⚠️ Warning: Profiling script missing, skipping symbolic execution..."
          else
            echo "Running symbolic execution on Ignition..."
            python3 scripts/profile_ignition.py --input=out.gn/x64.instrumented --output=ignition-profile.json || echo "⚠️ Warning: Profiling failed, continuing..."
          fi
        working-directory: v8

      - name: Analyze Profiling Data
        run: |
          if [ ! -f out.gn/x64.instrumented/ignition-profile.json ]; then
            echo "⚠️ Warning: Profiling data missing, skipping analysis..."
          else
            python3 scripts/analyze_symbolic_execution.py --input=out.gn/x64.instrumented/ignition-profile.json --output=symbolic-analysis.txt || echo "⚠️ Warning: Analysis failed, continuing..."
          fi
        working-directory: v8

      - name: Upload Profiling Results
        uses: actions/upload-artifact@v4
        with:
          name: ignition-symbolic-profile
          path: v8/out.gn/x64.instrumented/symbolic-analysis.txt
        if: always()
