name: Ignition Tests

on:
  workflow_call:

jobs:
  test-ignition:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Ignition Tests
        run: |
          tools/run-tests.py --outdir=out.gn/x64.release interpreter/ || echo "⚠️ Warning: Ignition tests failed, continuing..."
        working-directory: v8
